import React from 'react'
import { OpenSourceContributions } from '../public/data/Contributions'
import { LuExternalLink } from "react-icons/lu";
import { IoGitPullRequestSharp } from "react-icons/io5";

import Image from 'next/image'
const Description = ({ title,status,description,link }) => {
    return (
        <div className="mt-16">
            <div className="justify-between text-white border-0 border-red-500 md:flex">
                <div className="flex font-bold text-blue-400 sm1:text-lg md:text-xl"><span>{title}</span><span className="mt-1 ml-8"><a href={link} target="_blank"><LuExternalLink /></a></span></div>
                <div className={`p-2 w-fit md:ml-2 text-sm text-white ${status === 'Merged' ? 'bg-[#8957E5]' : 'bg-[#238636]'} rounded-xl flex`}><span className="mt-1 mr-2 text-sm"><IoGitPullRequestSharp /></span><span>{status}</span></div>
            </div>
            <div className="mt-2">{description}</div>
        </div>
    )
}

const Contributions = () => {
  return (
    <div className="mb-20 text-white">
        <div className="font-extrabold tracking-tighter text-center text-blue-400 sm1:text-xl sm1:p-6 md:pl-20 md:text-6xl">
            Open Source Contributions
        </div>
        <div className="font-extrabold tracking-tighter sm1:text-xl sm1:p-6 md:pl-20">
            About the Organisation _
        </div>
        <div className="sm1:p-6 md:p-20 lg:w-4/5 xl:w-3/5">
            <div className="text-5xl font-bold text-blue-400">GA4GH</div>
            <div className="mt-4">
                The mission of the Global Alliance for Genomics and Health (GA4GH) is to establish frameworks and standards for working with health-related and genomic data. Healthcare practitioners and researchers worldwide rely on this data to make informed decisions and improve treatments. Since the data, tools, and workflows involved are valuable resources, it&apos;s crucial that they can be located, accessed, and reused in a way that is interoperable. The GA4GH standards promote and maintain data principles across the biomedical data exchange and analysis field.
                <Image className="mt-10" alt="GA4GH logo" src="./media/contributions/ga4gh.png" height={500} width={500}></Image>
            </div>
        </div>
        <div className="ml-auto sm1:p-6 xl:w-3/5 md:p-20 lg:w-4/5">
            <div className="ml-auto font-bold text-blue-400 sm1:text-2xl md:text-5xl">About Elixir Cloud & AAI</div>
            <div className="md:pr-20">
                ELIXIR Cloud is a cloud-based infrastructure provided by the European life science infrastructure ELIXIR (European Life Science Infrastructure for Biological Information). The ELIXIR Cloud provides a range of services and tools for storing, sharing, and analyzing large volumes of data generated by life science research. These services include computing, data storage, and data management capabilities.AAI stands for Authentication and Authorization Infrastructure.It is a set of tools and policies that enable users to securely access and use resources across different services and infrastructures. AAI is critical for enabling secure and seamless collaboration between researchers and institutions, as well as for ensuring the privacy and security of sensitive data. ELIXIR Cloud utilizes AAI to provide secure access to its resources and services.
            </div>
            {/* <Image alt="elixir-logo" src="/media/contributions/elixir-aai.png" height={500} width={300}></Image> */}
        </div>
        <div className="font-extrabold tracking-tighter text-center text-blue-400 sm1:text-xl sm1:p-6 md:pl-20 md:text-6xl">
            Pull Requests
        </div>
        <div className="m-auto sm1:p-6 md:p-10 lg:p-20 lg:w-4/5 xl:w-3/5 md:mt-0">
            {
                OpenSourceContributions.map( (contri) => (
                    <Description title={contri.title} status={contri.status} description={contri.description} key={contri.id} link={contri.link}/>
                ))
            }
        </div>
    </div>
  )
}

export default Contributions
